modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Game-Stages"

[[mods]]
modId="gamestages"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.gamestages]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gamestages]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.gamestages]]
    modId="bookshelf"
    mandatory=true
    versionRange="[4.1,)"
    ordering="NONE"
    side="BOTH"